[project]
name = "brainbox-dashboard"
version = "0.0.12"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "art>=6.5",
    "httpx>=0.28.1",
    "psutil>=7.2.2",
    "python-nmap>=0.7.1",
    "textual>=8.2.8",
]
# executionEnvironments = [
#     {
#         "root": "src"
#     }
# ]

[dependency-groups]
dev = [
    "textual-dev>=1.8.0",
]
lint = [
    "ruff>=0.15.21",
]
test = [
    "pytest>=9.1.1",
]

# [tool.pyright]
# include = ["src"]

[tool.ruff]
line-length = 80

[tool.ruff.format]
docstring-code-format = true

[tool.ty.environment]
extra-paths = ["src"]
# python-platform = "linux"

[tool.basedpyright]
extraPaths = ["src"]

# [tool.setuptools.package-data]
# bbd = ["**/*.tcss"]

[project.scripts]
bbd = "main:run"
