[project]
name = "brainbox-dashboard"
version = "0.3.6"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "art>=6.5",
    "httpx>=0.28.1",
    "psutil>=7.2.2",
    "python-nmap>=0.7.1",
    "textual>=8.2.8",
    "textual-slider>=0.2.0",
]
# executionEnvironments = [
#     {
#         "root": "src"
#     }
# ]

[dependency-groups]
dev = [
    "textual-dev>=1.8.0",
]
lint = [
    "ruff>=0.15.21",
    "ty>=0.0.63",
]
test = [
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
]

# [tool.pyright]
# include = ["src"]

[tool.ruff]
line-length = 80

[tool.ruff.format]
docstring-code-format = true

[tool.ty.environment]
extra-paths = ["src"]
# python-platform = "linux"

[tool.ty.rules]
invalid-attribute-override = "ignore"

[tool.basedpyright]
extraPaths = ["src"]
reportIncompatibleVariableOverride = false

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]
asyncio_mode = "auto"

# [tool.setuptools.package-data]
# bbd = ["**/*.tcss"]

[project.scripts]
bbd = "main:run"
