name: Release
on: push
jobs:
  test_build_release:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install
        run: |
          pip install uv
          # uv venv
          # source .venv/bin/activate
          # uv sync --all-groups
          uv sync --no-group dev
      - name: lint
        run: uv run ruff check
      - name: Test
        run: uv run pytest
      - name: Build
        run: uv build
      - name: Release
        # only for release tags
        if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
          $(ls -d -1 "$PWD/dist/"*.*)#Wheel \
          --repo="$GITHUB_REPOSITORY" \
          --title="${tag#v}" \
          --generate-notes
